dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  device_apps: ^2.2.0        # ఫోన్ యాప్స్ లిస్ట్ కోసం
  installed_apps: ^1.4.1     # యాప్స్ ఓపెన్ చేయడానికి
  glassmorphism: ^3.0.0      # iOS బ్లర్ ఎఫెక్ట్ కోసం
